---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-service
    app: nodeapp
spec:
  selector:
    name: node-terraform
    app: todoapp
  ports:
  - port: 80
    name: node-port
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: node-replicas
  labels:
    name: node-terraform
    app: todoapp
spec:
  replicas: 2
  template:
    metadata:
      name: node-pod
      labels:
        name: node-terraform
        app: todoapp
    spec:
      containers:
      - name: node-container
        image: index.docker.io/uzzal2k5/node-terraform:latest
        env:
        - name: MONGODB_HOST
          value: mongodb
        ports:
        - containerPort: 8080
        #imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: database
spec:
  selector:
    name: mongodb
    app: database
  ports:
  - port: 27017
    name: db-port
    targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: database
spec:
  containers:
  - name: mongodb
    image: mongo:4.0.2
    ports:
    - containerPort: 27017